commercial_project/commercial_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu.urls'))
]

commercial_project/menu/urls.py
from django.urls import path
from . import views

handler404 = 'menu.views.handler404'


urlpatterns = [
    path('', views.index, name='index'),
]

commercial_project/menu/models.py
from django.db import models


class Menu(models.Model):
    title = models.CharField(max_length=50, null=False)
    url = models.CharField(max_length=255, null=False)
    parent_menu = models.ForeignKey('Menu', on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.title

commercial_project/menu/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')


def handler404(request, *args, **argv):
    response = render('404.html')
    response.status_code = 404
    return response

commercial_project/menu/templates/index.html
{% load static %}

<head>
    <meta charset="UTF-8" />
    <title>SHOP</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>

<body>
    <header>
        <h2 href="#">CYBEJABKA SHOP</h2>
        {% load menu_tags %}
        {% draw_menu 'Products' %}
        {% draw_menu 'Computers' %}
    </header>

    <section class="hero">
        <div class="background-image" style="background-image: url(https://wallpaper-house.com/data/out/9/wallpaper2you_297801.png)"></div>
        <div class="hero-content-area">
            <h1>Please write me</h1>
            <a href="https://t.me/cyberjabka" class="btn">TELEGRAM</a>
        </div>
    </section>

	<footer>
		<p>Made by CYBERJABKA</p>
	</footer>
</body>

commercial_project/menu/templates/menu.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/menu_tags.css' %}">

<nav id="primary_nav_wrap">
    <ul>
        {% for item in menu_items %}
        <li>
            <a href="{% if item.url %}{{ item.url }}{% else %}#{% endif %}"> {{ item.title }} </a>
            {% if item.menu_set.all %}
                <ul>
                    {% for subitem in item.menu_set.all %}
                        <li>
                            <a href="{% if subitem.url %}{{ subitem.url }}{% else %}#{% endif %}"> {{ subitem.title }} </a>
                            {% if subitem.menu_set.all %}
                            <ul>
                                {% for subsubitem in subitem.menu_set.all %}
                                <li>
                                        <a href="{% if subitem.url %}{{ subitem.url }}{% else %}#{% endif %}"> {{ subsubitem.title }} </a>
                                {% endfor %}
                                </li>
                            </ul>
                            {% endif %}
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </li>
    {% endfor %}
    </ul>
</nav>